/**
 * Minimal, documentation-aligned server upload handler for Vercel Blob.
 *
 * Summary of behavior (per @vercel/blob docs and SDK):
 * - Server-side `put()` requires a server read/write token (env: `BLOB_READ_WRITE_TOKEN` or passed via `token` option).
 * - Client-side uploads must use short-lived client tokens generated by a server endpoint — you should NOT expose the read/write token to the browser.
 *
 * This handler implements the straightforward server-side flow:
 * - reads the POST body as binary
 * - requires `x-file-name` + `content-type` headers
 * - uses `BLOB_READ_WRITE_TOKEN` from environment to call `put()`
 * - returns the blob `url` and `pathname` on success
 *
 * If no read/write token is configured, the handler returns a clear error explaining how to obtain and provide one.
 */

import { put } from '@vercel/blob';

export default async function handler(req: any, res: any) {
	if (req.method !== 'POST') {
		res.setHeader('Allow', 'POST');
		return res.status(405).json({ error: 'Method not allowed' });
	}

	const fileName = typeof req.headers['x-file-name'] === 'string' ? req.headers['x-file-name'] : 'upload.bin';
	const contentType = typeof req.headers['content-type'] === 'string' ? req.headers['content-type'] : 'application/octet-stream';

	async function readRequestBody(r: any): Promise<Uint8Array> {
		if (r.body && (r.body instanceof Uint8Array || (typeof Buffer !== 'undefined' && Buffer.isBuffer(r.body)))) {
			return r.body instanceof Uint8Array ? r.body : new Uint8Array(r.body);
		}

		if (typeof r.arrayBuffer === 'function') {
			try {
				const ab = await r.arrayBuffer();
				return new Uint8Array(ab);
			} catch {
				// continue to stream fallback
			}
		}

		const chunks: any[] = [];
		try {
			for await (const chunk of r) {
				chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
			}
		} catch {
			// ignore
		}

		if (chunks.length === 0) return new Uint8Array();
		return new Uint8Array(Buffer.concat(chunks));
	}

	try {
		const payload = await readRequestBody(req);
		if (!payload || payload.byteLength === 0) return res.status(400).json({ error: 'No file body provided' });

		const writeToken = process.env.BLOB_READ_WRITE_TOKEN || process.env.BLOB_READ_WRITE_TOKENS?.split(',')?.[0] || null;

		if (!writeToken) {
			return res.status(501).json({
				error: 'Server-side blob upload requires a read/write token',
				guidance: [
					'Generate a Read or Read+Write token for your Vercel Blob store in the Vercel dashboard: Integrations → Vercel Blob → Stores → <your store> → API tokens',
					'Add the token to your project environment variables as BLOB_READ_WRITE_TOKEN (or VERCEL_BLOB_TOKENS as comma-separated)',
					'See: https://vercel.com/docs/storage/vercel-blob for details',
				],
			});
		}

		const result = await put(fileName, Buffer.from(payload), {
			access: 'public',
			contentType,
			addRandomSuffix: false,
			token: writeToken,
		});

		return res.status(200).json({ url: result.url, pathname: result.pathname, contentType: result.contentType, size: payload.byteLength });
	} catch (err) {
		console.error('upload handler error', err instanceof Error ? err.stack || err.message : String(err));
		return res.status(500).json({ error: 'Upload failed', message: err instanceof Error ? err.message : String(err) });
	}
